# Generated by Django 3.0.6 on 2020-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplattername',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizzaname',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='salad',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sub',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='subname',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
    ]
